apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-action-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      dockerMTU: 1400
      repository: praveenkpatidar/my-go-app
      labels:
        - "actions_runner_dev"
        - "default"
      env:
        - name: ARC_DOCKER_MTU_PROPAGATION
          value: "true"
        - name: RUNNER_TOKEN
          value: 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
      nodeSelector:
        dedicated: github-runner
      tolerations:
        - key: dedicated
          operator: Equal
          value: github-runner
          effect: NoSchedule
